#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ThucTap_Android.Resource", IsApplication=true)]

namespace ThucTap_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_create = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_redo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_content_save = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_content_undo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_social_share = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int man_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monkey = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int btnCapNhat = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int btnHuy = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int btnNgaySinh = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int btnNgaySinh_Sua = 2131165194;
			
			// aapt resource value: 0x7f07001a
			public const int btnQuayVe = 2131165210;
			
			// aapt resource value: 0x7f070015
			public const int btnThem = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int btn_DangNhap_Login = 2131165213;
			
			// aapt resource value: 0x7f070013
			public const int cbNam = 2131165203;
			
			// aapt resource value: 0x7f07000b
			public const int cbNam_Sua = 2131165195;
			
			// aapt resource value: 0x7f070014
			public const int cbNu = 2131165204;
			
			// aapt resource value: 0x7f07000c
			public const int cbNu_Sua = 2131165196;
			
			// aapt resource value: 0x7f07001c
			public const int edt_MatKhau_Login = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int edt_TaiKhoan_Login = 2131165211;
			
			// aapt resource value: 0x7f07000f
			public const int extHoLot = 2131165199;
			
			// aapt resource value: 0x7f070007
			public const int extHoLot_Sua = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int extMaBN = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int extMaBN_Sua = 2131165190;
			
			// aapt resource value: 0x7f070011
			public const int extNgaySinh = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int extNgaySinh_Sua = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int extTen = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int extTen_Sua = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int imgIcon = 2131165184;
			
			// aapt resource value: 0x7f070020
			public const int listBenhNhan = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int main_content = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int menu_Them = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int menu_ThongKe = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int menu_sua = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int menu_xoa = 2131165220;
			
			// aapt resource value: 0x7f07001e
			public const int toolbar = 2131165214;
			
			// aapt resource value: 0x7f070005
			public const int txtGioiTinh = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int txtHoLot = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int txtMaBenhNhan = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int txtNgaySinh = 2131165188;
			
			// aapt resource value: 0x7f070019
			public const int txtSoLuongKXD = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int txtSoLuongNam = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int txtSoLuongNu = 2131165208;
			
			// aapt resource value: 0x7f070003
			public const int txtTen = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BenhNhan_HienThi_Layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BenhNhan_Item_Layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BenhNhan_Sua_Layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BenhNhan_Them_Layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int BenhNhan_ThongKe_Layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login_Layout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int sua_xoa_item = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int link = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
